const db = require('./db');
const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all();
console.log('Tables:', tables.map(t => t.name).join(', '));
const xp = db.prepare('SELECT COUNT(*) as c FROM xp_log').get();
console.log('XP records:', xp.c);
const ach = db.prepare('SELECT COUNT(*) as c FROM user_achievements').get();
console.log('Achievements:', ach.c);
const chall = db.prepare('SELECT COUNT(*) as c FROM challenges').get();
console.log('Challenges:', chall.c);
const streak = db.prepare('SELECT COUNT(*) as c FROM streaks').get();
console.log('Streaks:', streak.c);
